#!/bin/sh

inp="$1"

open -a /Applications/MacVim.app/Contents/MacOS/MacVim "$inp" 

exit

os=$(uname)



case "$os" in
  Darwin)
    [ -f "$inp" ] || touch "$inp"
  if which mvim > /dev/null ; then 
     if mvim --serverlist | grep VIEW > /dev/null ; then
       # -M :readonly
        #mvim -M --servername VIEW --remote $inp
        mvim  --servername VIEW --remote $inp
     else
        mvim  --servername VIEW $inp
     fi
  else
    die "Err: no mvim"
  fi
osascript <<'EOF'
tell application "System Events"
   tell  process "MacVim"        
        set frontmost to true
       perform action "AXRaise" of (first window whose name contains "VIEW")
   end tell
end tell
EOF
    ;;
  *)
    echo "Err: os $os not implemented yet"
    exit 1
    ;;
esac
