#!/bin/sh

target_default=mp3

dir=$1
target=$2

[ -d "$dir" ] || { echo "usage:<dir>"; exit 1; }
[ -n "$target" ] || target=$target_default


translate () {
  local f=$1
  bf=$(basename "$f")
  df=$(dirname "$f")

  bfn=${bf%.*}

  case "$bf" in
    *flac)
      [ -f "$df/$bfn.mp3" ] || ffmpeg -i "$f" "$df/$bfn.mp3"
      ;;
    *)
      :
      ;;
  esac

}

for i in "$dir"/* ; do
  if [ -f "$i" ] ; then
     translate "$i"
  elif [ -d "$i" ] ; then
   for f in "$i"/*.flac ; do
     [ -f "$f" ] || continue
     translate "$f"
   done
  else
    echo "Warn: omit $i"
  fi
done
