#!/bin/sh

target_default=mp3

dir=$1
target=$2

[ -d "$dir" ] || { echo "usage:<dir>"; exit 1; }
[ -n "$target" ] || target=$target_default


for f in "$dir/"* ; do
  [ -f "$f" ] || continue
  bf=$(basename "$f")
  df=$(dirname "$f")

  bfn=${bf%.*}
  echo bb $bf
      echo xxx "$df/$bfn.$target"

  case "$bf" in
    *.mp4)
   if [ -f "$df/$bfn.$target" ] ; then
      rm -f "$f"
    else
      ffmpeg -i "$f" "$df/$bfn.$target" && rm -f "$f"
    fi
    ;;
  *.m4a)
   if [ -f "$df/$bfn.$target" ] ; then
      rm -f "$f"
    else
      ffmpeg "$df/$bfn.$target" -i "$f" -codec:a libmp3lame -qscale:a 1 && rm -f "$f"
    fi
    ;;
  *)
    :
    ;;
esac

done
