execute pathogen#infect()
syntax on
filetype plugin indent on




" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
"call plug#begin('~/.vim/plugged')
"Plug 'https://github.com/Alok/notational-fzf-vim'
"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
" Initialize plugin system
"call plug#end()
"
if has("gui_running")
syntax on
	set hlsearch
	colorscheme slate
	"set	guifont=Monaco:h15
  if has("gui_gtk2")
    set guifont=Inconsolata\ 14
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h16
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  else
    set guifont=Monospace\ 12
  endif
	set bs=2
	set ai
	set ruler
endif



set shell=/bin/sh

let mapleader=","
let maplocalleader=","

set modelines=1

set nu
set noerrorbells
set vb t_vb=


set nocompatible
behave xterm
filetype plugin indent on
syntax on

if !empty(glob(expand("~/.vim/bundle")))
   execute pathogen#infect()

	"au VimEnter * RainbowParenthesesToggle
	"au Syntax * RainbowParenthesesLoadRound
	"au Syntax * RainbowParenthesesLoadSquare
	"au Syntax * RainbowParenthesesLoadBraces
endif



for fpath in split(globpath('~/.vimrc.d/', '*.vim'), '\n')
   exe 'source' fpath
endfor

set laststatus=2

au VimEnter * syntax keyword Statement lambda conceal cchar=λ
au VimEnter * hi! link Conceal Statement
au VimEnter * set conceallevel=2
set ruler


" Faster buffer switch
nnoremap <Leader>b :ls<CR>:b<Space>


syntax enable
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

au BufReadPost *.w set syntax=perl
autocmd BufReadPost *.org call OrgModeHi('perl', 'perl')
autocmd BufReadPost *.org call OrgModeHi('bash', 'sh')
autocmd BufReadPost *.org call OrgModeHi('emacs-lisp', 'lisp')

syn region JakeTitle start="<<" end=">>"
highlight JakeTitle ctermbg=black ctermfg=yellow



" gui colors
set background=dark
hi SpecialKey guifg=Blue
hi MoreMsg guifg=Green
hi Visual guifg=NONE guibg=NONE
hi Folded ctermbg=4 guibg=Blue
hi FoldColumn ctermbg=7
hi DiffAdd guibg=Blue
hi DiffChange guibg=Magenta
hi DiffDelete guibg=Cyan
hi Normal guifg=Gray guibg=Black
hi Cursor guibg=White
hi lCursor guibg=White
hi Comment guifg=Cyan
hi Constant guifg=Magenta
hi Special guifg=Red
hi Identifier guifg=Cyan
hi Statement guifg=Yellow
hi PreProc guifg=Blue
hi Type guifg=Green
hi Underlined guifg=Blue
hi Todo guifg=Black

set showtabline=2
set guioptions+=e



if executable("opam") 
	let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
   execute "set rtp+=" . g:opamshare . "/merlin/vim"
" run manually: :execute "helptags " . substitute(system('opam config var share'),'\n$','','''') .  "/merlin/vim/doc"
"set rtp+=/Users/bkb/.opam/4.06.1/share/merlin/vim
"
endif


inoremap <C-Space> <C-x><C-o>
inoremap <C-@> <C-Space>
inoremap <C-@> <c-x><c-o>
let g:slime_target = "tmux"

"let g:vim_parinfer_globs = ['*.fnl']
"let g:vim_parinfer_globs = ['*.lisp', '*.fnl', '*.scm']
"let g:vim_parinfer_filetypes: ['lisp']
