# ~/.bash_profile:
#
# bash specific environment variables

if [ -r ~/.profile ]; then 
   . ~/.profile; 
fi

case "$-" in 
   *i*) 
      if [ -r ~/.bashrc ]; then 
         . ~/.bashrc; fi
    ;; 
esac


# Explanations

# Bash startup files loading order
#
# from https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/
#
# For Bash, they work as follows. Read down the appropriate column. Executes A, then B, then C, etc. The B1, B2, B3 means it executes only the first of those files found.
#
#  +----------------+-----------+-----------+------+
#  |                |Interactive|Interactive|Script|
#  |                |login      |non-login  |      |
#  +----------------+-----------+-----------+------+
#  |/etc/profile    |   A       |           |      |
#  +----------------+-----------+-----------+------+
#  |/etc/bash.bashrc|           |    A      |      |
#  +----------------+-----------+-----------+------+
#  |~/.bashrc       |           |    B      |      |
#  +----------------+-----------+-----------+------+
#  |~/.bash_profile |   B1      |           |      |
#  +----------------+-----------+-----------+------+
#  |~/.bash_login   |   B2      |           |      |
#  +----------------+-----------+-----------+------+
#  |~/.profile      |   B3      |           |      |
#  +----------------+-----------+-----------+------+
#  |BASH_ENV        |           |           |  A   |
#  +----------------+-----------+-----------+------+
#  |                |           |           |      |
#  +----------------+-----------+-----------+------+
#  |                |           |           |      |
#  +----------------+-----------+-----------+------+
#  |~/.bash_logout  |    C      |           |      |
#  +----------------+-----------+-----------+------+

export PATH="$HOME/.cargo/bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/bkb/.sdkman"
[[ -s "/Users/bkb/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/bkb/.sdkman/bin/sdkman-init.sh"
export HOMEBREW_GITHUB_API_TOKEN=2f46a32d824965607d82ce9e447e4aa0501b4b71

# nvm node version manager
export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
